// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

import { implicitReturnType } from '../base/types.js';
import { Exchange as _Exchange } from '../base/Exchange.js';

interface Exchange {
    publicGetMarketdataPairOrderbook (params?: {}): Promise<implicitReturnType>;
    publicGetMarketdataPairOrderbookFull (params?: {}): Promise<implicitReturnType>;
    publicGetCurrencies (params?: {}): Promise<implicitReturnType>;
    publicGetPairs (params?: {}): Promise<implicitReturnType>;
    publicGetOrdertypes (params?: {}): Promise<implicitReturnType>;
    publicGetPairOrdertypes (params?: {}): Promise<implicitReturnType>;
    publicGetMarketsummary (params?: {}): Promise<implicitReturnType>;
    publicGetPairMarketsummary (params?: {}): Promise<implicitReturnType>;
    publicGetPairMarkpriceBuckets (params?: {}): Promise<implicitReturnType>;
    publicGetPairTrades (params?: {}): Promise<implicitReturnType>;
    publicGetPairFuturesFundingHistory (params?: {}): Promise<implicitReturnType>;
    publicGetTime (params?: {}): Promise<implicitReturnType>;
    publicGetStatus (params?: {}): Promise<implicitReturnType>;
    privateGetAccountApiKeysCurrent (params?: {}): Promise<implicitReturnType>;
    privateGetAccountBalances (params?: {}): Promise<implicitReturnType>;
    privateGetAccountTransactionhistory (params?: {}): Promise<implicitReturnType>;
    privateGetAccountFeesTrade (params?: {}): Promise<implicitReturnType>;
    privateGetMarketdataPairOrderbook (params?: {}): Promise<implicitReturnType>;
    privateGetMarketdataPairTradehistory (params?: {}): Promise<implicitReturnType>;
}
abstract class Exchange extends _Exchange {}

export default Exchange
